# Generated by Django 3.0.6 on 2020-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200525_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(to='web.Category', verbose_name='دسته بندی'),
        ),
    ]
