# Generated by Django 3.0.7 on 2020-06-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='web.Category', verbose_name='دسته بندی'),
        ),
    ]
