# Generated by Django 3.0.7 on 2020-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200626_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('D', 'پیش نویس'), ('P', 'منتشر شده'), ('I', 'در حال بررسی'), ('B', 'تایید نشده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
